build:
  uri: https://github.com/wildfly/quickstart.git
  ref: 31.0.0.Final
  contextDir: micrometer
deploy:
  replicas: 1
  env:
    - name: OTEL_COLLECTOR_HOST
      value: "opentelemetrycollector"
