name: WildFly Quickstarts CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  Test-build-default-matrix:
    name: BUILD DEFAULT - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build Quickstarts Release
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'

  Test-build-with-deps-matrix:
    name: BUILD WITH DEPS - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: [ubuntu-20.04, windows-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        repository: wildfly/wildfly
        ref: ${{ github.base_ref }}
        path: wildfly
    - uses: actions/checkout@v4
      with:
        path: quickstarts
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'temurin'
        cache: 'maven'
    - name: Build Server
      run: |
        cd wildfly
        mvn -U -B -fae -DskipTests clean install
      shell: bash
    - name: Get Server Version
      run: |
        cd wildfly
        echo "VERSION_SERVER=$(mvn -N org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      shell: bash
    - name: Build Quickstarts Release with Server and BOMs Versions
      run: |
        cd quickstarts
        mvn -U -B -fae clean install -Drelease -Dversion.server.bom=${{ env.VERSION_SERVER }} -Dversion.microprofile.bom=${{ env.VERSION_SERVER }} -Dversion.server.bootable-jar=${{ env.VERSION_SERVER }} -Dversion.server=${{ env.VERSION_SERVER }}
      shell: bash
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: surefire-reports-JDK${{ matrix.jdk }}-${{ matrix.os }}
        path: 'quickstarts/**/surefire-reports/*.txt'